-- Create normalized tables for travelers and flight segments

CREATE TABLE IF NOT EXISTS travelers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  booking_id INT NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  title VARCHAR(10),
  gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
  date_of_birth DATE NOT NULL,
  email VARCHAR(255),
  phone_country_code VARCHAR(5),
  phone_number VARCHAR(20),
  nationality VARCHAR(2),
  country_of_residence VARCHAR(2),
  passenger_type ENUM('adult', 'child', 'infant', 'seated_infant', 'senior') DEFAULT 'adult',
  age INT,
  provider_passenger_id VARCHAR(100),
  special_requests TEXT,
  meal_preference VARCHAR(50),
  seat_preference VARCHAR(50),
  frequent_flyer_programs JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  INDEX idx_booking (booking_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS traveler_documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  traveler_id INT NOT NULL,
  document_type ENUM('passport', 'national_id', 'visa', 'drivers_license') DEFAULT 'passport',
  document_number VARCHAR(50) NOT NULL,
  issuing_country VARCHAR(2) NOT NULL,
  nationality VARCHAR(2),
  issue_date DATE,
  expiry_date DATE NOT NULL,
  issuing_authority VARCHAR(100),
  place_of_issue VARCHAR(100),
  is_valid BOOLEAN DEFAULT TRUE,
  validated_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (traveler_id) REFERENCES travelers(id) ON DELETE CASCADE,
  INDEX idx_traveler (traveler_id),
  INDEX idx_document (document_number)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS flight_segments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  flight_order_id INT NOT NULL,
  segment_number INT NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_city VARCHAR(100),
  departure_terminal VARCHAR(10),
  departure_time DATETIME NOT NULL,
  arrival_airport VARCHAR(3) NOT NULL,
  arrival_city VARCHAR(100),
  arrival_terminal VARCHAR(10),
  arrival_time DATETIME NOT NULL,
  marketing_carrier VARCHAR(3),
  marketing_carrier_name VARCHAR(100),
  marketing_flight_number VARCHAR(10),
  operating_carrier VARCHAR(3),
  operating_carrier_name VARCHAR(100),
  operating_flight_number VARCHAR(10),
  aircraft_code VARCHAR(10),
  aircraft_name VARCHAR(100),
  duration VARCHAR(20),
  duration_minutes INT,
  distance DECIMAL(10,2),
  cabin_class ENUM('economy', 'premium_economy', 'business', 'first') DEFAULT 'economy',
  booking_class VARCHAR(2),
  fare_basis VARCHAR(20),
  checked_bags_included INT DEFAULT 0,
  cabin_bags_included INT DEFAULT 1,
  number_of_stops INT DEFAULT 0,
  is_codeshare BOOLEAN DEFAULT FALSE,
  co2_emissions INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (flight_order_id) REFERENCES flight_orders(id) ON DELETE CASCADE,
  INDEX idx_flight_order (flight_order_id),
  INDEX idx_route (departure_airport, arrival_airport),
  INDEX idx_departure (departure_time)
) ENGINE=InnoDB;
